#################################################################
###################### Hexo Configuration #######################
#################################################################

# Site
title: Monkeys Blog
keywords: "Adnan, Sulejmanovic"
language: ba
timezone: Europe/Sarajevo

# URL
url: https://monkeyshub.space
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: stars
archive_dir: cosmos
category_dir: black_hole
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - robots.txt
  - animate/*
  - highlight/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''

meta_generator: true

# Home page setting
index_generator:
  per_page: 5
  order_by: -date

# Category & Tag
default_category: black_hole
category_map:
tag_map:

# Date / Time format
date_format: DD.MM.YYYY
time_format: HH:mm:ss

# Pagination
per_page: 5
pagination_dir: stranica

# Extensions
theme: next

archive_generator:
  per_page: 9
  yearly: false
  monthly: false
  daily: false

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  lazyload: true

search:
  path: search.json
  field: all

sitemap:
  path: sitemap.xml
  rel: true
  tags: true
  categories: true
